"""Build db/market.db from the processed CSVs and refresh sql/RESULTS.md.

Executing the queries as part of the load is deliberate. RESULTS.md is committed so a reader can
see real output without running anything, and regenerating it here means the committed output
can never drift away from the committed data.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path

import pandas as pd
from tabulate import tabulate

ROOT = Path(__file__).resolve().parents[1]
PROCESSED_DIR = ROOT / "data" / "processed"
SQL_DIR = ROOT / "sql"
DB_PATH = ROOT / "db" / "market.db"
RESULTS_PATH = SQL_DIR / "RESULTS.md"

DISCLOSURE = (
    "Illustrative dataset constructed to be directionally consistent with publicly reported "
    "industry estimates. Figures are for methodology demonstration and are not market research."
)

# Load order matters: dim_segment first so the foreign keys resolve.
TABLES = [
    ("dim_segment", "dim_segment.csv"),
    ("fact_segment_year", "fact_segment_year.csv"),
    ("fact_opportunity_score", "fact_opportunity_score.csv"),
    ("fact_sensitivity", "fact_sensitivity.csv"),
]


def build_database() -> sqlite3.Connection:
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    DB_PATH.unlink(missing_ok=True)

    connection = sqlite3.connect(DB_PATH)
    connection.executescript((SQL_DIR / "00_schema.sql").read_text())

    for table, filename in TABLES:
        frame = pd.read_csv(PROCESSED_DIR / filename)
        frame.to_sql(table, connection, if_exists="append", index=False)

    connection.execute("PRAGMA foreign_keys = ON")
    violations = connection.execute("PRAGMA foreign_key_check").fetchall()
    if violations:
        raise RuntimeError(f"foreign key violations after load: {violations}")

    connection.commit()
    return connection


def query_files() -> list[Path]:
    return sorted(p for p in SQL_DIR.glob("*.sql") if p.name != "00_schema.sql")


def leading_comment(sql_text: str) -> str:
    """The comment block at the top of each query file is its documentation; reuse it verbatim."""
    lines = []
    for line in sql_text.splitlines():
        if not line.startswith("--"):
            break
        lines.append(line.lstrip("-").strip())
    return "\n".join(lines).strip()


def write_results(connection: sqlite3.Connection) -> None:
    parts = [
        "# Query results",
        "",
        f"> {DISCLOSURE}",
        "",
        "Generated by `src/load_sqlite.py` against `db/market.db`. Every table below is real "
        "output from the query file named above it, not a transcription.",
        "",
    ]

    for path in query_files():
        sql_text = path.read_text()
        frame = pd.read_sql_query(sql_text, connection)

        parts.append(f"## `{path.name}`")
        parts.append("")
        parts.append(leading_comment(sql_text))
        parts.append("")
        parts.append(f"Rows returned: {len(frame)}")
        parts.append("")
        parts.append(tabulate(frame, headers="keys", tablefmt="github", showindex=False))
        parts.append("")

    RESULTS_PATH.write_text("\n".join(parts).rstrip() + "\n")


def main() -> None:
    connection = build_database()
    try:
        counts = {
            table: connection.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0]
            for table, _ in TABLES
        }
        write_results(connection)
    finally:
        connection.close()

    print(f"database: {DB_PATH} " + ", ".join(f"{t}={n}" for t, n in counts.items()))
    print(f"results:  {RESULTS_PATH} ({len(query_files())} queries executed)")


if __name__ == "__main__":
    main()
